SUPABASE_URL = "https://nrhwruxrcdskfmhdyoow.supabase.co"  
SUPABASE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yaHdydXhyY2Rza2ZtaGR5b293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4Mjk2NzYsImV4cCI6MjEwNTQwNTY3Nn0.8Wwr6phZbR4Li-wVVScfw7mLq3u7fPoHLcYAYNmcGP0"
RAZORPAY_KEY_ID = "rzp_test_TdzFHC5g59WdWj"
RAZORPAY_KEY_SECRET = "DKbwc67T9LRB69Nrux6YGURh" 